export const genres = [
  'anime',
  'biography',
  'actions',
  'western',
  'military',
  'detectives',
  'kids',
  'documentaries',
  'drama',
  'play',
  'historical',
  'comedy',
  'shortFilm',
  'criminal',
  'melodrama',
  'music',
  'cartoons',
  'musical',
  'news',
  'adventures',
  'realTv',
  'family',
  'sport',
  'talkShow',
  'thrillers',
  'horror',
  'fantastic',
  'noir',
  'fantasy',
];

export const countries = [
  'Australia',
  'Argentina',
  'Belarus',
  'Belgium',
  'Germany',
  'India',
  'Denmark',
  'Spain',
  'Canada',
  'China',
  'Russia',
  'USA',
  'Finland',
  'SouthKorea',
  'France',
  'Italy',
];

export const ratings = ['9', '8', '7', '6'];

export const estimates = ['300000', '400000', '500000', '600000', '700000', '800000', '900000', '1000000'];
